apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  labels:
    app: grafana
    perfeng.io/managed-by: perfeng
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin
