apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    {{- include "perfeng-infra.labels" . | nindent 4 }}