duration: 30m
maxVUs: 1000

stages:
  - duration: 5m
    target: 100
  - duration: 5m
    target: 300
  - duration: 5m
    target: 500
  - duration: 5m
    target: 750
  - duration: 5m
    target: 1000
  - duration: 5m
    target: 0

thresholds:
  checkout_duration: ['p(95)<800']
  http_req_failed: ['rate<0.05']
