namespace: kube-system

image:
  repository: registry.k8s.io/metrics-server/metrics-server
  tag: v0.7.1
  pullPolicy: IfNotPresent

args:
  certDir: /tmp
  securePort: 10250
  kubeletPreferredAddressTypes: InternalIP,ExternalIP,Hostname
  kubeletUseNodeStatusPort: true
  kubeletInsecureTls: true
  metricResolution: 15s

strategy:
  rollingUpdate:
    maxUnavailable: 0

priorityClassName: system-cluster-critical

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

nodeSelector:
  kubernetes.io/os: linux

probes:
  readiness:
    path: /readyz
    port: 10250
    scheme: HTTPS
    failureThreshold: 3
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    path: /livez
    port: 10250
    scheme: HTTPS
    failureThreshold: 3
    periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 400Mi
