apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: metrics-server
    {{- include "perfeng-infra.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    k8s-app: metrics-server