duration: 10m
maxVUs: 500

stages:
  - duration: 2m
    target: 100
  - duration: 2m
    target: 300
  - duration: 3m
    target: 500
  - duration: 3m
    target: 0

thresholds:
  checkout_duration: ['p(95)<1000']
  http_req_failed: ['rate<0.1']
