apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
  labels:
    app: minio
    {{- include "perfeng-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app: minio