apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: node-exporter
    {{- include "perfeng-infra.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app: node-exporter