apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    {{- include "perfeng-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.credentials.user | default "admin" }}
  admin-password: {{ .Values.credentials.password | default "admin" }}