apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
    perfeng.io/component: sut
    perfeng.io/managed-by: perfeng
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: http-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -text="PerfEng SUT"
            - -listen=:{{ .Values.service.port }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}