apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: perf-platform
  labels:
    app: minio
    perfeng.io/component: storage
    perfeng.io/managed-by: perfeng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
