---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoles.nodeReader.name }}
  labels:
    perfeng.io/component: rbac
    {{- include "perfeng-infra.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/status", "nodes/metrics"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoles.prometheus.name }}
  labels:
    perfeng.io/component: rbac
    {{- include "perfeng-infra.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]