---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.generatorManager.name }}
  namespace: {{ .Values.roles.generatorManager.namespace }}
  labels:
    perfeng.io/component: rbac
    {{- include "perfeng-infra.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.sutReader.name }}
  namespace: {{ .Values.roles.sutReader.namespace }}
  labels:
    perfeng.io/component: rbac
    {{- include "perfeng-infra.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]