---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.orchestrator.name }}
  namespace: {{ .Values.serviceAccounts.orchestrator.namespace }}
  labels:
    perfeng.io/component: orchestrator
    {{- include "perfeng-infra.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.generator.name }}
  namespace: {{ .Values.serviceAccounts.generator.namespace }}
  labels:
    perfeng.io/component: generator
    {{- include "perfeng-infra.labels" . | nindent 4 }}