platformNamespace: perf-platform
generatorsNamespace: perf-generators
sutNamespace: perf-sut

resourceQuotas:
  platform:
    requestsCpu: '2'
    requestsMemory: '4Gi'
    limitsCpu: '4'
    limitsMemory: '8Gi'
    pods: '20'
    services: '10'
    configmaps: '20'
    secrets: '10'
    persistentvolumeclaims: '5'

  generators:
    requestsCpu: '4'
    requestsMemory: '8Gi'
    limitsCpu: '8'
    limitsMemory: '16Gi'
    pods: '30'
    services: '5'
    configmaps: '30'
    secrets: '10'
    persistentvolumeclaims: '5'

  sut:
    requestsCpu: '4'
    requestsMemory: '8Gi'
    limitsCpu: '8'
    limitsMemory: '16Gi'
    pods: '30'
    services: '20'
    configmaps: '30'
    secrets: '10'
    persistentvolumeclaims: '10'

limitRanges:
  platform:
    container:
      defaultCpu: '500m'
      defaultMemory: '512Mi'
      defaultRequestCpu: '100m'
      defaultRequestMemory: '128Mi'
      maxCpu: '2'
      maxMemory: '2Gi'
      minCpu: '50m'
      minMemory: '64Mi'
    pod:
      maxCpu: '4'
      maxMemory: '4Gi'
      minCpu: '100m'
      minMemory: '128Mi'

  generators:
    container:
      defaultCpu: '500m'
      defaultMemory: '512Mi'
      defaultRequestCpu: '100m'
      defaultRequestMemory: '128Mi'
      maxCpu: '2'
      maxMemory: '2Gi'
      minCpu: '50m'
      minMemory: '64Mi'
    pod:
      maxCpu: '4'
      maxMemory: '4Gi'
      minCpu: '100m'
      minMemory: '128Mi'

  sut:
    container:
      defaultCpu: '500m'
      defaultMemory: '512Mi'
      defaultRequestCpu: '100m'
      defaultRequestMemory: '128Mi'
      maxCpu: '2'
      maxMemory: '2Gi'
      minCpu: '50m'
      minMemory: '64Mi'
    pod:
      maxCpu: '4'
      maxMemory: '4Gi'
      minCpu: '100m'
      minMemory: '128Mi'
